/**
 * Player stats data loading functions
 * @module data/playerstats
 */

import { HttpClient } from '../client/client.js';
import { getConfig } from '../config/manager.js';
import type { Season } from '../types/common.js';
import { DataNotFoundError, Err, NetworkError, Ok, type Result } from '../types/error.js';
import type {
  LoadPlayerStatsOptions,
  PlayerStatsData,
  PlayerStatsRecord,
  SummaryLevel,
} from '../types/player-stats.js';

import { createLogger, type Logger } from '../utils/logger.js';
import { parseCsv, parseParquet } from '../utils/parse.js';
import { normalizeSeasons } from '../utils/seasons.js';
import { buildPlayerStatsUrl } from '../utils/url.js';
import { assertValidSeason } from '../utils/validation.js';

// Lazy logger initialization to avoid module-level side effects
let logger: Logger | undefined;
const getLogger = () => logger ?? (logger = createLogger('loadPlayerStats'));

/**
 * Load player statistics for one or more NFL seasons
 *
 * This function fetches player statistics from the nflverse data repository
 * (the `stats_player` release, generated by nflfastR::calculate_stats). One
 * combined file covers passing, rushing, receiving, defensive, kicking, and
 * special teams statistics. Files are pre-aggregated per summary level, so
 * `summaryLevel` selects which file is downloaded.
 *
 * @param seasons - Season(s) to load. Can be:
 *   - A single season number (e.g., 2023)
 *   - An array of seasons (e.g., [2022, 2023])
 *   - `true` to load all available seasons (1999-present)
 *   - `undefined` to load the current season
 * @param options - Additional options for loading data
 * @returns Result containing array of player stats records or an error
 *
 * @example
 * ```typescript
 * // Load current season weekly stats
 * const stats = await loadPlayerStats();
 *
 * // Load specific season
 * const stats2023 = await loadPlayerStats(2023);
 *
 * // Load multiple seasons
 * const statsMulti = await loadPlayerStats([2022, 2023]);
 *
 * // Load regular season totals
 * const regStats = await loadPlayerStats(2023, { summaryLevel: 'reg' });
 *
 * // Load postseason totals
 * const postStats = await loadPlayerStats(2023, { summaryLevel: 'post' });
 *
 * // Load combined regular + postseason totals
 * const fullStats = await loadPlayerStats(2023, { summaryLevel: 'reg+post' });
 *
 * // Load with parquet format (faster, smaller file size)
 * const statsParquet = await loadPlayerStats(2023, { format: 'parquet' });
 * ```
 *
 * @see {@link https://nflreadr.nflverse.com/reference/load_player_stats.html | nflreadr::load_player_stats}
 */
export async function loadPlayerStats(
  seasons?: Season | Season[] | true,
  options: LoadPlayerStatsOptions = {}
): Promise<Result<PlayerStatsData, Error>> {
  const { format = 'csv', summaryLevel = 'week' } = options;

  try {
    // Determine which seasons to load
    const seasonsToLoad = normalizeSeasons(seasons);

    getLogger().debug(
      `Loading player stats for seasons: ${seasonsToLoad.join(', ')}, level: ${summaryLevel}`
    );

    // Validate all seasons upfront
    for (const season of seasonsToLoad) {
      assertValidSeason(season);
    }

    // Create a single HttpClient instance for all requests
    const config = getConfig();
    const client = new HttpClient({
      timeout: config.http.timeout,
      retry: config.http.retries,
      cache: config.cache.enabled,
      cacheTtl: config.cache.ttl,
      debug: config.logging.debug,
    });

    // Load data for each season in parallel
    const results = await Promise.all(
      seasonsToLoad.map((season) => loadPlayerStatsForSeason(season, format, summaryLevel, client))
    );

    // Optimize array concatenation - collect all arrays first, then concat once
    const dataArrays: PlayerStatsData[] = [];
    for (const result of results) {
      if (result.ok) {
        dataArrays.push(result.value);
      } else {
        // If any season fails, return the error
        return result;
      }
    }

    // Single concatenation is much faster than repeated spread operations
    const allData =
      dataArrays.length === 1 ? dataArrays[0]! : ([] as PlayerStatsData).concat(...dataArrays);

    getLogger().debug(`Loaded ${allData.length} player stats records`);

    return Ok(allData);
  } catch (error) {
    getLogger().error('Failed to load player stats', error);
    return Err(error instanceof Error ? error : new Error(String(error)));
  }
}

/**
 * Load player stats for a single season
 */
async function loadPlayerStatsForSeason(
  season: Season,
  format: 'csv' | 'parquet',
  summaryLevel: SummaryLevel,
  client: HttpClient
): Promise<Result<PlayerStatsData, Error>> {
  try {
    // Build URL for the season's data; the summary level selects which
    // pre-aggregated stats_player file nflverse publishes
    const url = buildPlayerStatsUrl(season, summaryLevel, format);

    getLogger().debug(`Fetching player stats from: ${url}`);

    // Fetch the data
    const response = await client.get(url);

    if (response.status !== 200) {
      return Err(
        new DataNotFoundError(`Player stats not found for season ${season}`, {
          season,
          url,
          status: response.status,
          summaryLevel,
        })
      );
    }

    // Parse based on format
    let data: PlayerStatsData;
    if (format === 'parquet') {
      // Parse parquet data from ArrayBuffer
      const buffer = response.data as ArrayBuffer;
      data = await parseParquet<PlayerStatsRecord>(buffer);
    } else {
      // Parse CSV data from string
      const csvString =
        typeof response.data === 'string'
          ? response.data
          : new TextDecoder().decode(response.data as ArrayBuffer);
      const parseResult = parseCsv<PlayerStatsRecord>(csvString);
      data = parseResult.data;
    }

    getLogger().debug(
      `Parsed ${data.length} player stats records for season ${season} (level: ${summaryLevel})`
    );

    return Ok(data);
  } catch (error) {
    if (error instanceof Error) {
      getLogger().error(`Failed to load player stats for season ${season}`, error);

      // Convert to appropriate error type
      if (error.message.includes('fetch') || error.message.includes('network')) {
        return Err(
          new NetworkError(`Network error loading player stats for season ${season}`, {
            season,
            originalError: error.message,
          })
        );
      }

      return Err(error);
    }

    return Err(new Error(`Unknown error loading player stats for season ${season}`));
  }
}
