/**
 * Team stats data loading functions
 * @module data/teamstats
 */

import type { HttpClient } from '../client/client.js';
import type { Season } from '../types/common.js';
import { DataNotFoundError, Err, NetworkError, Ok, type Result } from '../types/error.js';
import type { SummaryLevel } from '../types/player-stats.js';
import type { LoadTeamStatsOptions, TeamStatsData, TeamStatsRecord } from '../types/team-stats.js';

import { createLogger, type Logger } from '../utils/logger.js';
import { normalizeSeasons } from '../utils/seasons.js';
import { buildTeamStatsUrl } from '../utils/url.js';
import { assertValidSeason } from '../utils/validation.js';
import { concatSeasons, createDataClient, fetchParsedAsset } from './internal.js';

// Lazy logger initialization to avoid module-level side effects
let logger: Logger | undefined;
const getLogger = () => logger ?? (logger = createLogger('loadTeamStats'));

/**
 * Load team statistics for one or more NFL seasons
 *
 * This function fetches team statistics from the nflverse data repository
 * (the `stats_team` release, generated by nflfastR::calculate_stats). One
 * combined file covers passing, rushing, receiving, defensive, kicking, and
 * special teams statistics aggregated to the team level. Files are
 * pre-aggregated per summary level, so `summaryLevel` selects which file is
 * downloaded.
 *
 * @param seasons - Season(s) to load. Can be:
 *   - A single season number (e.g., 2023)
 *   - An array of seasons (e.g., [2022, 2023])
 *   - `true` to load all available seasons (1999-present)
 *   - `undefined` to load the current season
 * @param options - Additional options for loading data
 * @returns Result containing array of team stats records or an error
 *
 * @example
 * ```typescript
 * // Load current season weekly team stats
 * const stats = await loadTeamStats();
 *
 * // Load specific season
 * const stats2023 = await loadTeamStats(2023);
 *
 * // Load multiple seasons
 * const statsMulti = await loadTeamStats([2022, 2023]);
 *
 * // Load regular season totals
 * const regStats = await loadTeamStats(2023, { summaryLevel: 'reg' });
 *
 * // Load postseason totals
 * const postStats = await loadTeamStats(2023, { summaryLevel: 'post' });
 *
 * // Load combined regular + postseason totals
 * const fullStats = await loadTeamStats(2023, { summaryLevel: 'reg+post' });
 *
 * // Load with parquet format (faster, smaller file size)
 * const statsParquet = await loadTeamStats(2023, { format: 'parquet' });
 * ```
 *
 * @see {@link https://nflreadr.nflverse.com/reference/load_team_stats.html | nflreadr::load_team_stats}
 */
export async function loadTeamStats(
  seasons?: Season | Season[] | true,
  options: LoadTeamStatsOptions = {}
): Promise<Result<TeamStatsData, Error>> {
  const { format = 'csv', summaryLevel = 'week' } = options;

  try {
    // Determine which seasons to load
    const seasonsToLoad = normalizeSeasons(seasons);

    getLogger().debug(
      `Loading team stats for seasons: ${seasonsToLoad.join(', ')}, level: ${summaryLevel}`
    );

    // Validate all seasons upfront
    for (const season of seasonsToLoad) {
      assertValidSeason(season);
    }

    const client = createDataClient();

    // Load data for each season in parallel
    const results = await Promise.all(
      seasonsToLoad.map((season) => loadTeamStatsForSeason(season, format, summaryLevel, client))
    );

    const dataArrays: TeamStatsData[] = [];
    for (const result of results) {
      if (result.ok) {
        dataArrays.push(result.value);
      } else {
        // If any season fails, return the error
        return result;
      }
    }

    const allData = concatSeasons(dataArrays);

    getLogger().debug(`Loaded ${allData.length} team stats records`);

    return Ok(allData);
  } catch (error) {
    getLogger().error('Failed to load team stats', error);
    return Err(error instanceof Error ? error : new Error(String(error)));
  }
}

/**
 * Load team stats for a single season
 */
async function loadTeamStatsForSeason(
  season: Season,
  format: 'csv' | 'parquet',
  summaryLevel: SummaryLevel,
  client: HttpClient
): Promise<Result<TeamStatsData, Error>> {
  // Build URL for the season's data; the summary level selects which
  // pre-aggregated stats_team file nflverse publishes
  const url = buildTeamStatsUrl(season, summaryLevel, format);

  try {
    getLogger().debug(`Fetching team stats from: ${url}`);

    const data = await fetchParsedAsset<TeamStatsRecord>(client, url, format);

    getLogger().debug(
      `Parsed ${data.length} team stats records for season ${season} (level: ${summaryLevel})`
    );

    return Ok(data);
  } catch (error) {
    if (error instanceof Error) {
      getLogger().error(`Failed to load team stats for season ${season}`, error);

      // Convert to appropriate error type
      if (error instanceof DataNotFoundError) {
        return Err(
          new DataNotFoundError(`Team stats not found for season ${season}`, {
            season,
            url,
            summaryLevel,
          })
        );
      }

      if (error.message.includes('fetch') || error.message.includes('network')) {
        return Err(
          new NetworkError(`Network error loading team stats for season ${season}`, {
            season,
            originalError: error.message,
          })
        );
      }

      return Err(error);
    }

    return Err(new Error(`Unknown error loading team stats for season ${season}`));
  }
}
